version: '3'
services:
  mysqldb:
    image: mysql:8.0
    environment:  
      MYSQL_DATABASE: citylibrary
      MYSQL_ROOT_PASSWORD: CityLibrary123
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: